# Generated by Django 4.2.3 on 2023-11-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Advice/')),
                ('tex', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Akademiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bg_photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Baho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Baho/')),
                ('name', models.CharField(max_length=200)),
                ('play', models.IntegerField()),
                ('gol', models.IntegerField()),
                ('durrang', models.IntegerField()),
                ('defeat', models.IntegerField()),
                ('tf', models.IntegerField()),
                ('ball', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg', models.URLField()),
                ('fb', models.URLField()),
                ('youtube', models.URLField()),
                ('logo', models.ImageField(upload_to='Bosh/')),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='Bosh/')),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bozar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Bozar/')),
                ('command_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Bozor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Coach/')),
                ('name', models.CharField(max_length=220)),
                ('first_name', models.CharField(max_length=220)),
                ('tex', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Cup/')),
                ('title', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('photo', models.ImageField(upload_to='frame/')),
            ],
        ),
        migrations.CreateModel(
            name='Hamkor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Hamkor/')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=346)),
            ],
        ),
        migrations.CreateModel(
            name='Img_stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Img_stadium/')),
            ],
        ),
        migrations.CreateModel(
            name='Info_club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tex', models.TextField()),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jadval_malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ball', models.IntegerField()),
                ('logo', models.ImageField(upload_to='jadval_malumot/')),
            ],
        ),
        migrations.CreateModel(
            name='Komanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Komanda/')),
                ('title', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Komanda_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bal', models.IntegerField()),
                ('logo', models.ImageField(upload_to='Komanda_info/')),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('photo', models.ImageField(upload_to='leadership/')),
            ],
        ),
        migrations.CreateModel(
            name='Malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Malumot/')),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='Malumot/')),
                ('data', models.DateField()),
                ('tg', models.URLField()),
                ('fb', models.URLField()),
                ('youtube', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Malumot_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('photo', models.ImageField(upload_to='malumot_info/')),
            ],
        ),
        migrations.CreateModel(
            name='Malumot_magazin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='malumot_magazin/')),
            ],
        ),
        migrations.CreateModel(
            name='Maydon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('text', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Maydon_o',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Maydon_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Maydonm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='My_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('bg_img', models.ImageField(upload_to='')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Play/')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('pasition', models.CharField(max_length=200)),
                ('geyms', models.IntegerField()),
                ('start', models.IntegerField()),
                ('sap', models.IntegerField()),
                ('minuts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Player/')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('orni', models.CharField(max_length=300)),
                ('game', models.IntegerField()),
                ('start', models.IntegerField()),
                ('sap', models.IntegerField()),
                ('minuts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ramaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('photo', models.ImageField(upload_to='Ramaka/')),
            ],
        ),
        migrations.CreateModel(
            name='Reyting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Reyting/')),
                ('name', models.CharField(max_length=200)),
                ('oyin', models.IntegerField()),
                ('gol', models.IntegerField()),
                ('durrang', models.IntegerField()),
                ('maglubiyat', models.IntegerField()),
                ('tf', models.IntegerField()),
                ('ball', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('title', models.TextField()),
                ('photo_1', models.ImageField(upload_to='')),
                ('photo_2', models.ImageField(upload_to='')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tex', models.TextField()),
                ('place', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('photo', models.ImageField(upload_to='Team/')),
            ],
        ),
        migrations.CreateModel(
            name='Vide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Vide/')),
                ('name', models.CharField(max_length=200)),
                ('video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Video/')),
                ('name', models.CharField(max_length=200)),
                ('video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Stadion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('tex', models.TextField()),
                ('size', models.IntegerField()),
                ('sector', models.IntegerField()),
                ('locations', models.CharField(max_length=300)),
                ('number', models.IntegerField()),
                ('photo', models.ManyToManyField(to='main.img_stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Club/')),
                ('title', models.CharField(max_length=200)),
                ('tex', models.TextField()),
                ('photo2', models.ImageField(upload_to='Club/')),
                ('info', models.ManyToManyField(to='main.info_club')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('jadval_malumot', models.ManyToManyField(to='main.jadval_malumot')),
            ],
        ),
        migrations.CreateModel(
            name='Best',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('Komanda_info', models.ManyToManyField(to='main.komanda_info')),
            ],
        ),
    ]
