from django.urls import path
from .views import *

urlpatterns = [
    path('get-bosh', get_bosh),
    path('get-ramaka/', get_ramaka),
    path('get-komanda/', get_komanda),
    path('get-komanda_info/', get_komanda_info),
    path('get-best/', get_best),
    path('get-video/', get_video),
    path('get-reyting', get_reyting),
    path('get-player/', get_player),
    path('get-malumot_magazin/',get_malumot_magazin),
    path('get-bozor/', get_bozor),
    path('get-stadium/', get_stadium),
    path('get-malumot/',  get_malumot),
    path('get-frame/',  get_frame),
    path('get-cup/', get_cup),
    path('get-jadval_malumot', get_jadval_malumot),
    path('get-calendar/',  get_calendar),
    path('get-baho/', get_baho),
    path('get-vide/', get_vide),
    path('get-play/',  get_play),
    path('get-malumot_info/', get_malumot_info),
    path('get-bozar/', get_bozar),
    path('get-img_stadium/', get_img_stadium),
    path('get-stadion', get_stadion),
    path('get-hamkor/', get_hamkor),
    path('get-team/', get_team),
    path('get-leadership', get_leadership),
    path('get-coach/', get_coach),
    path('get-info_club /', get_info_club),
    path('get-club/', get_club),
    path('get-advice/', get_advice),
    path('get-akademiya/',  get_akademiya),
    path('get-activities', get_activities),
    path('get-my_shop',  get_my_shop),
    path('get-shopping ', get_shopping),
    path('get-img/',  get_img),
    path('get-maydonm /', get_maydonm),
    path('get-maydon_t/', get_maydon_t),
    path('get-maydon_o ', get_maydon_o),
    path('get-maydon', get_maydon),
]